# PCD转Nav2栅格地图参数配置文件
# 所有路径建议用绝对路径，避免相对路径找不到文件
pcd_path: "./src/rm_bnrobot_nav/maps/pcd/test.pcd"  # 输入PCD文件路径
save_dir: "/home/mage/navigation/nav_RM_4/src/rm_bnrobot_nav/maps"                    # 输出地图保存目录
resolution: 0.05                                                                      # 栅格分辨率（米/像素，推荐0.05~0.1）
z_min: 0.0                                                                            # 点云Z轴最小值（过滤地面以下噪声，根据机器人高度调整）
z_max: 0.55                                                                            # 点云Z轴最大值（过滤高空噪声，根据障碍物高度调整）
